#  configuration: production

spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3307/webdb?charset=utf8
      username: webdb
      password: '{cipher}AQCbjGAoqSw9+Bl+PMH10tnfkyelb61TSQt7yZCbsZBUtbRA5RrwKP6E/qcr53mxUG2p7T4OKQbnOmO1IcH6VhGr1xpQn93kxJHj2PWVgHqvQbsVpAqD8Qjqhuqa7ykQEHvlVEEJbhhiCtU/3TRzg6wL0JmPRXcG0E3YlzfsDCFPjLwx9yQ98rHnoziPpfNoMXVF8UuLDPnGitq2LMHEhkZpfBv8nWtzR8GoxtuDY+2yMhmR0L/qsL5qQ12EY3uVRMmgslnqOrJ84ExtI4TD1mxCq4VK7Csb57SY4tg66UJma81F5NjY+1VEworAuqerX8Q2idJpK4Ab3427MAcv75Iz06e1LuoyCOdKF3QziP49dOpWRhTkw9jx0xHXWBeF7wg='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            msa:
               service:
                  gallery:
                     exception: ERROR
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.180:8761/eureka