#
# development configuration
spring:
   config:
      activate:
         on-profile: development

   devtools:
      livereload:
         enabled: true

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.180:3307/webdb?characterEncoding=utf8
      username: webdb
      password: '{cipher}AQAtSHylgzcbjH2jtmyXjICFMLfqrzdF3v9rgkAnsZTNW/94hkgEKtxNMnb3383a7rZr7uBt35t6L4s/UtcHcFqfyID8xvshGbVijB+8y7s8rYUWF+2D6MJzNzyou3/ijeAhLIpxMuffG046OP3LCgY5ce4bWqhEP+65JD5TDKlGkgcfE26zTJF4A7HX1ESyM7F2ZmI3BDOeDV0aFaNQIZL05yquHH8bVqHi6MB5Jp6QH0t1hFy4HGUnqI4Y7BbRlu4rEKMOTbhlIDeoAUOVOTkXoMojmBJX+m8ATMmISFvy13JhbJa4wqH6dC3FXohfhMjhafk6DP+jzSg+9N83G629ddZGKJAmyyFJkFQArdm+AxRyzlthNVbRGtqjWYmvmCQ='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   