# configuration: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.180:3307/webdb?charset=utf8
      username: webdb
      password: '{cipher}AQCnOU2oibP8Kti0c+HExGo5y6Qar7Ld+80wyQqK5C1qTm33Q+3WdI5xbfyj1ehnE9rs+7MrLxfSN5QH9NJA3TaSPZfL+Mmc3hrz8TLngq9gKKi2jWHrPv+hQ5GrX/3R6GANVlGJ+pkIpADqMxFDWL7GF4e8tIPvoEG2oElRpp3cZYxX49+EDJhiPe/MTri86ypv3j1oYEFDms1bD02I258tD3yx61a6+j1PEO5AS17xShrzPOng+3W8w9O+pLF9K5p443NlMtF5GaZvIPBiDu5GiPGBZQ6A1ZGjlhswUulShNaJWKnJ6BHD2qGzFH6Ytqq21PfaHd97r7CzPEGygjy4O06PXmuYGv1626atGwW9TH/Ft+oAPygO+wjgQ8IeYlk='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            msa:
               service:
                  guestbook:
                     exception: ERROR
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.180:8761/eureka